### 课程大纲

1. 错误
2. Panic异常
3. Recover捕获异常

### 上一课作业答案解析

无

### 本次课堂内容

#### 1、错误

#### 2、Panic异常

#### 3、Recover捕获异常

```
package main

import "fmt"

func main() {

	fmt.Println("Starting the program")
	p()
	fmt.Println("Ending the program")
}
func p(){
	defer func() {
		err := recover() //内置的recover可以捕获异常
		if err != nil {
			fmt.Println("err=", err)
		}
	}()
	panic("A severe error occurred: stopping the program!")
	fmt.Println("12123123")
}
```

### 练习题

### 补充说明

### 课程链接